# Generated by Django 2.1.4 on 2019-04-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='status',
            field=models.CharField(default='arriving', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='flight',
            unique_together={('name', 'departure_time')},
        ),
    ]
