# Generated by Django 2.1.4 on 2019-04-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20190417_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
