# Generated by Django 2.1.4 on 2019-04-17 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_auto_20190417_0839'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('letter', 'row', 'flight')},
        ),
    ]
