# Generated by Django 2.1.4 on 2019-04-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_auto_20190417_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
